---

language: cpp
dist: focal
arch:
  - amd64
  - arm64
osx_image: xcode11.6

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      arch: arm64

addons:
  apt:
    packages:
      - libxml2-dev
      - libpng-dev
      - libjpeg-dev
      - libjpeg-turbo8
      - libsdl2-dev
      - libfreetype6-dev
      - libsigc++-2.0-dev
      - uuid-dev
      - freeglut3-dev
      - libantlr4-runtime-dev
      - libmpv-dev
  homebrew:
    packages:
      - freetype
      - libsigc++@2
      - libtool
      - antlr@4
      - antlr4-cpp-runtime
    #update: true

install:
  - git clone https://github.com/geekprojects/libgeek.git; cd libgeek; mkdir build; cd build; cmake ..; make; if [ "$TRAVIS_OS_NAME" == "osx" ]; then make install; else sudo make install; sudo ldconfig; fi; cd -

before_script:
  - mkdir build; cmake ..

script:
  - make && sudo make install && tests/tests

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

